### ISSUE TITLE
La date ne s’affiche pas sur l’écran verrouillé

### ISSUE THREAD

**Issue by SapeurPonpier** [Snowy1803/FrenchRepublicanCalendar#2]
Bonjour,

La date du calendrier ne s’affiche pas correctement et le « placeholder » ne se remplace pas par la date républicaine après personnalisation sur mon appareil (iPhone 13 pro).

![AA2BA63C-8355-4191-88AA-73B5CDEE68AF](https://user-images.githubusercontent.com/15271621/192095789-c41a4843-ecb2-476a-9316-d91216358007.jpeg)

La date s’affiche pourtant correctement au choix du widget.

![1ABF038D-3E64-4338-8EE4-8DA17C962A5D](https://user-images.githubusercontent.com/15271621/192095880-6a1222c0-039a-49c1-8e74-5b2511e3b794.jpeg)

Merci pour cette super application !

**Comment by Snowy1803** [comment]
Il semblerait que si j'essaye de générer 39+ widgets à l'avance, le widget crash car il passe au dessus de la limite de 30 Mo de RAM. Si je le met à 38 widgets à l'avance, il n'utilise que 6 Mo.
C'est très étrange, je vais envoyer un feedback à Apple.
Pour l'instant je vais le mettre à 38, ce sera corrigé dans la prochaine mise à jour.

Merci pour votre commentaire !

**Comment by SapeurPonpier** [comment]
Super ! Une indication sur la date de sortie de la mise à jour ?

**Comment by Snowy1803** [comment]
La 6.3 sortira ce week-end, je viens de la soumettre

**Comment by Snowy1803** [comment]
La 6.3 est sortie sur l'App Store aujourd'hui, il ne devrait donc plus y avoir ce problème
